# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту prostokota@list.ru если сборка упала
notifications:
  email:
    recipients:
      prostokota@list.ru
    on_success: never # default: change
    on_failure: always # defa,ult: always

env:
  global:
    - CODECOV_TOKEN="fd52ab93-903c-4633-b9ee-0ba870c263a8"